apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: aws-auth 
  namespace: kube-system 
data: 
  mapUsers: | 
    - userarn: arn:aws:iam::320964430417:user/Bank_Application
      username: Bank_Application
      groups:
        - system:masters
