apiVersion: v1
kind: Service
metadata:
  name: simple-bank-api-service
spec:
  selector:
    app: simple-bank-api
  ports:
    - name: bank-api-port
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: redis-port
      protocol: TCP
      port: 6379
      targetPort: 6379
  type: LoadBalancer
